### PR TITLE
Create new codeql.yml file

### LINKED ISSUE #5: add dependabot and codeql to the commit workflow
I think it would be a good practice to add dependabot as well as CodeQL to our pipelines

### PR DESCRIPTION
**Pull request by deanone**
Setting up the CodeQL tool for the repo.

### CODE REVIEW

**Comment by deanone** [comment]
@phkrief the check eclipsefdn/eca fails for some reason. When I click the "Details" button next to the check it shows me this figure:

codeql_fail

My primary email address on GitHub is athanasios.salamanis@gmail.com. The same email address I used for signing the ICA. Also, I have changed my email address on Eclipse Foundation profile from asal@iti.gr to athanasios.salamanis@gmail.com.

Yet, I keep getting a failure on the eclipsefdn/eca check.

Any thoughts on how to resolve this and proceed with merging the PR?

**Comment by deanone** [comment]
@phkrief an update:

In the Eclipse Foundation site I get the following message in a "Tips" box:

_Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA._

Maybe this helps you understand what is going on

**Comment by phkrief** [comment]
@eclipsewebmaster,
May I ask you to have the kindness to check out this point?
Thx a lot

**Comment by mazanekj** [comment]
@phkrief @deanone I have quickly checked and I don't see any obvious issue with either ECA installation for the eclipse-opensmartclide organization or with the Athanasios's EF profile.
I suggest, that you open a helpdesk issue under https://gitlab.eclipse.org/eclipsefdn/helpdesk and we will look into it more closely

**Comment by deanone** [comment]
> @phkrief @deanone I have quickly checked and I don't see any obvious issue with either ECA installation for the eclipse-opensmartclide organization or with the Athanasios's EF profile. I suggest, that you open a helpdesk issue under https://gitlab.eclipse.org/eclipsefdn/helpdesk and we will look into it more closely

@mazanekj ok I'll do that. Until I have a response from the helpdesk, I will not proceed with merging the PR. Thanks

**Comment by chrisguindon** [comment]
This should be fixed now. I posted an update here:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2092#note_1027927

The root of the issue here is that there is 3 PRs with exactly the same commit. The system is not able to handle this properly.

https://github.com/eclipse-opensmartclide/smartclide-broker/pull/9 https://github.com/eclipse-opensmartclide/smartclide-broker/pull/8 https://github.com/eclipse-opensmartclide/smartclide-broker/pull/6

I had to update our database to clean this up manually and now this commit validates.

In case of ECA failures like this one, project committers can accept a contribution after validating that the user has an ECA on file. This can by visiting the user account https://accounts.eclipse.org/users/asalamanis

The status block should indicate if the user has an ECA on file. When doing this, it's important to validate using the email address that was used in the author field. That information is easily available via GitHub API: https://api.github.com/repos/eclipse-opensmartclide/smartclide-broker/pulls/9/commits

**Comment by deanone** [comment]
Ok, I understand @chrisguindon. So, the committer should have as primary email address (i.e., the email address identified by GitHub API when the commit is made) the same as the one used for signing the ECA.

**Comment by chrisguindon** [comment]
@deanone Yes, that would be the ideal situation!

**Comment by deanone** [comment]
> @deanone Yes, that would be the ideal situation!

Thanks @chrisguindon

**Pull request merged**
